### ISSUE TITLE
remove doc completion count for practice docs

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#122]
----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/122
- Originally reported by: [Andrew Su](http://bitbucket.org/asu)
- Originally created at: 2015-07-22T23:51:27.854

**Comment by x0xMaximus** [comment]
This is the new practice group page in which you can see the documents that are designated as training: https://mark2cure.org/group/training/

While I don't recall when this issue was created, it doesn't seem to be relevant anymore. Rather than showing completions, our training documents always remain at empty. If we would like to change how to visually showing documents or quests or any tasks that are considered training we should discuss this from a UI / UX perspective

![](http://i.imgur.com/8jQG6R4.png)
