### ISSUE TITLE
annotation out of thin air bug

### ISSUE THREAD

**Issue by gtsueng** [SuLab/mark2cure#139]
Still needs further investigation, but it looks like annotations in the 'frequent list' for the talk page on this doc appeared from no where. Under 'diseases', the term 'wilms' and 'tumour' are listed, but after doing a ctrl-f search for 'wilms' in the abstract in pubmed, still not able to figure out where that term came from. Checked all the user's markings, and none of them have marked these two terms.
![2016 04 22 - wtf](https://cloud.githubusercontent.com/assets/9200138/14747965/11adf38c-086c-11e6-9b1f-b11d90277412.PNG)

The PMID for this doc should be: 701378

**Comment by JTFouquier** [comment]
@gtsueng this is an odd one. I'll look into it too, but Max is definitely more familiar with this code.

**Comment by JTFouquier** [comment]
This was fixed with these commits 263cd7bedea9ec0cd299d7335668a66c3eb3cba7 and 79e795647703afd8d566992d229d4f18b7891bef  (pushed to home_scroll branch then merged to master) .... error was in SQL custom query that stemmed from integration of the relation app into m2c. Now we use "concept_type" to identify if relation or entity recognition task.
