### ISSUE TITLE
Mobile: side popup instruction not visible

### ISSUE THREAD

**Issue by gtsueng** [SuLab/mark2cure#157]
The instruction box on https://mark2cure.org/training/relation/1/step/5/ is not fully visible on mobile. In Windows Nokia, Android LG, and Iphone5, only the 'box' portion of the popover instruction text could be seen. Users can't swipe left to see it either in most cases.

Suggestion: for mobile, have it below the 'relates to' box.

**Comment by JTFouquier** [comment]
@gtsueng as a quick fix I could just make them all placed below instead of on the left. 

@x0xMaximus what is the best way to do JS checks for window/browser size so I can dynamically change the location of the popover when on mobile?  Because this popover placement is written in JS, I wasn't sure how to check for grid size.
