### ISSUE TITLE
Synopsis view and access to talk pages

### ISSUE THREAD

**Issue by gtsueng** [SuLab/mark2cure#171]
A user mentioned being able to discuss the relationships on the talk pages, which cannot be done yet.

**Comment by gtsueng** [comment]
Priority features of this is:
1. access to talk page & inform user of bonus points earned
2. ability to go to next quest instead of returning to dashboard
3. synopsis view of their submissions (not important at this time and may be a separate ticket if needed)

**Comment by x0xMaximus** [comment]
1. ~~access to talk page~~ & inform user of bonus points earned
2. ability to go to next quest instead of returning to dashboard
3. ~~synopsis view of their submissions (not important at this time and may be a separate ticket if needed)~~

@gtsueng is the review bonus points earned fulfilled by following:

- ![](http://i.imgur.com/vdQZdZj.png)
- Or the odometer point increasing per relation task comparison complete

Either way, I believe that "inform user of bonus points earned" is also considered done but want to confirm. Seems like the only remaining issue is 2, or the automatic routing of users to the next relationship task set. Did we want to separate that out into it's own discrete issue now as the way we prioritize what relation tasks are done in what order becomes more sophisticated?

**Comment by x0xMaximus** [comment]
The automated option to go to the next relationship document isn't implemented, but given the amount of work we'll put into developing the way relationship tasks are presented and completed I'm going to consider this closed as all the other components are completed


![](http://i.imgur.com/EUfSE1I.png)
