### ISSUE TITLE
Point total reporting is confusing

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#6]
On the training 2 feedback (http://mark2cure.org/training/intro/2/step/feedback/), we report "Points gained: 2,000".  

![12-2-2014 12-54-34 PM.jpg](https://bitbucket.org/repo/y7oq9p/images/29663806-12-2-2014%2012-54-34%20PM.jpg)

I interpret that to mean 2000 from that training quest, but that's really my point total (1,000 for each training quest).  

I think it would be more clear to have a feedback reporting like this:

![12-2-2014 12-43-07 PM.jpg](https://bitbucket.org/repo/y7oq9p/images/1010113834-12-2-2014%2012-43-07%20PM.jpg)

----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/6
- Originally reported by: [Andrew Su](http://bitbucket.org/asu)
- Originally created at: 2014-12-02T21:56:43.523

**Comment by x0xMaximus** [comment]
@gtsueng this page is from prior of having 2 tasks so that url isn't around anymore but would be considered /training/entity-recognition/intro/2/step/feedback/ – seeing as how this is very similar to #102 is it safe to close this as well? The approach I took for #102 was that it goes 0 > 4,000 animation, then for this page it goes 4,000 > 8,000 points animation (and then again from 8 > 12k for the last step). Is that how we wanted to leave it or did we want to add further copy to explain it further.

It currently looks like this after the odometer animation runs ![](http://i.imgur.com/TXRR5A4.png)

**Comment by x0xMaximus** [comment]
@gtsueng just pinging again to check up on this. Can this be closed now give how it's,  currently handle, if not can you direct me on specifically how we could sum the point total
