### ISSUE TITLE
SEO discussion

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#69]
What can we do here on the site itself?  Just opening this up for discussion.
How much traffic is coming through search now?

Straightforward Ideas:
SiteMap
More 'refer a friend' links

Harder:
Content farm..  Bring abstracts and such into the site to enable search traffic via keywords within them.  (needs a lot of thought)

---
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/69
- Originally reported by: [bgood](http://bitbucket.org/bgood)
- Originally created at: 2015-02-05T21:30:57.637

**Comment by JTFouquier** [comment]
One thing that stands out is the authentications requirements. We have so much content but in order to edit / contribute to any of it you need to be authenticated which can't be indexed. We'd build up a lot of pages if we have a /document/123/public page or something that visualized the communities efforts in some way – only real point of the page being to expose those document pages to a crawler with lots of text and links on it

I've done a lot of the meta and og header tags that we can for social sharing.

Inbound links are critical

----------------------------------------
Original comment by: [Max Nanis](http://bitbucket.org/x0xMaximus)

**Comment by x0xMaximus** [comment]
1. I need to go through the Facebook and Twitter metatags as we're seeing share links with empty cover images.
2. I need to cleanup the robots file for our public pages like mark2cure.org/instructions/ as there is a ton of search content on there that we could probably get organic traffic from.

**Comment by x0xMaximus** [comment]
Updating this to include a recent discussion with @gtsueng about making og and twitter page specific tags

**Comment by gtsueng** [comment]
Here are the results of a spider crawl through our site as well as suggested changes for title and meta description tags. Lowest hanging fruit for on page SEO will be title and meta description.  Not as concerned with keywords since the main search engines these days don't use them (except for baidu).  H1 and H2 tag content is also taken into consideration in SEO, but will affect the actual appearance of the page (title and meta description won't by much).  Note that while we have publicly viewable user pages, there isn't a good way to get to them without knowing the url, or logging in to view the leader board or clicking on the word clouds, so the spider didn't make it that far.  https://docs.google.com/spreadsheets/d/1MOqeTTth0XVs7Da9JHDsYTZtherzDvIwd6kmIpHrX74/edit#gid=0
